# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: decordel <decordel@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2022/03/28 16:59:39 by decordel          #+#    #+#              #
#    Updated: 2022/03/28 17:13:34 by decordel         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = tet

all	: ${NAME}

${NAME}	: readline_t.c
	gcc -lreadline readline_t.c -o ${NAME}

do	:
	make
	./tet
